---
- name: Upgrade packages
  apt: upgrade=safe
  become: yes
  
- name: Install applications via snap
  command:
  args:
    argv:
      - snap
      - install
      - docker
      - gitkraken
      - intellij-idea-community
      - ngrok
      - postman
      - spotify
      - vlc
      - vscode
  become: yes

- name: Install dbeaver
  apt:
    deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
  become: yes

- name: Install google chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: yes

- name: Install franz
  apt:
    deb: https://github.com/meetfranz/franz/releases/download/v{{ franz_version }}/franz_{{ franz_version }}_amd64.deb
  become: yes

- name: Installing openvpn
  package:
    name: openvpn
    state: present
  become: yes

- name: Installing python pip
  package:
    name: python-pip
    state: present
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
  become: yes    
