---
- name: Upgrade packages
  apt: upgrade=safe
  become: yes
  
- name: Install applications via snap
  snap:
    name:
      - docker
      - gitkraken
      - ngrok
      - postman
      - spotify
      - vlc

- name: Install intellij and vscode via snap
  snap:
    name:
      - intellij-idea-community
      - vscode
    classic: yes

- name: Install dbeaver
  apt:
    deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
  become: yes

- name: Install google chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: yes

- name: Install franz
  apt:
    deb: https://github.com/meetfranz/franz/releases/download/v{{ franz_version }}/franz_{{ franz_version }}_amd64.deb
  become: yes

- name: Installing openvpn
  package:
    name: openvpn
    state: present
  become: yes

- name: Installing python pip
  package:
    name: python-pip
    state: present
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
  become: yes

- name: Download anki
  unarchive:
    src: "https://apps.ankiweb.net/downloads/current/anki-{{ anki_version }}-linux-amd64.tar.bz2"
    dest: "{{ lookup('env','HOME') }}/Downloads/"
    remote_src: yes

- name: Install anki
  command: bash -lc "cd {{ lookup('env','HOME') }}/Downloads/anki-{{ anki_version }}-linux-amd64 && make install"
  become: yes
