---
- name: Upgrade packages
  apt: upgrade=safe
  become: yes
  
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - curl
  - git
  - git-flow
  - unrar
  - vim
  - xclip
  become: yes

- name: Setup default git configuraiton
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "Paulo" }
    - {name: "user.email", value: "paulo.vitor@aisdigital.com.br" }
    - {name: "ui.color",   value: "true" }